//===- QThreadImpl.cpp ----------------------------------------------------===//
//
//                            The Bold Project
//
//  This file is distributed under the New BSD License.
//  See LICENSE for details.
//
//===----------------------------------------------------------------------===//
#include <bold/Thread/ThreadImpl.h>

using namespace bold;

//===----------------------------------------------------------------------===//
// QThreadImpl - Quick Thread
//===----------------------------------------------------------------------===//

